# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "my-label=true"
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 31080
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 32080
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 33080
networking:
  disableDefaultCNI: true
